[project]
name = "train-deploy-mnist-cnn"
version = "0.1.0"
description = "To train and deploy an Mnist model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentationsx>=2.0.10",
    "aws-cdk-lib>=2.214.0",
    "gradio>=5.44.1",
    "lightning>=2.5.5",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torch-lr-finder>=0.2.2",
    "torch-summary>=1.4.5",
    "torchaudio>=2.8.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
]
